version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/python
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run: pip install "whisk==0.1.29"
      - run: whisk setup
      - python/save-cache
      - run: echo "source /home/circleci/project/venv/bin/activate" >> $BASH_ENV
      - run: whisk dvc setup
      - run: dvc pull
      - run:
          command: pytest -s
          name: Test Project
      - run:
          command: whisk notebook run notebooks/explore.ipynb
          name: Test Notebook
      - run:
          # only python 3.7 is installed
          command: tox -e py37
          name: Test Package

workflows:
  main:
    jobs:
      - test
